//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcudirET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public string Observacion { get; set; }
        public decimal PrecioFinal { get; set; }
        public int MedioPagoId { get; set; }
        public int ClienteId { get; set; }
        public int RepartidorId { get; set; }
        public int EstadoId { get; set; }
        public int ProductoId { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        public virtual MedioDePago MedioDePago { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Repartidor Repartidor { get; set; }
    }
}
